[project]
name = "framework-example"
version = "1.0.0"
description = ""
authors = [{ name = "James Sweet", email = "jsweet@nd.edu" }]
requires-python = ">=3.8,<=3.11"
license = { text = "MIT" }
dependencies = ["torch", "torchvision", "dvc[gdrive]", "dvclive"]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
